services:
    postgres_db:
        image: postgres:17.0
        ports:
            - ${TRUNCT_DATABASE_PORT:-5432}:5432
        environment:
            - POSTGRES_USER=${TRUNCT_DATABASE_USER}
            - POSTGRES_PASSWORD=${TRUNCT_DATABASE_PASSWORD}
            - POSTGRES_DB=${TRUNCT_DATABASE_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    air_development:
        image: cosmtrek/air:v1.61.1
        working_dir: /app
        depends_on:
            - postgres_db
        ports:
            - 3333:3333
        environment:
            - LOAD_ENV_FILE=true
        volumes:
            - ./:/app
        command:
            [
                "--build.cmd",
                "GOOS=linux CGO_ENABLED=0 GOARCH=amd64 GO111MODULE=on go build -buildvcs=false -o ./bin/api ./cmd/api",
                "--build.bin",
                "./bin/api",
            ]

volumes:
    postgres_data:
        driver: local
