services:
    postgres_db:
        image: postgres:17.0
        ports:
            - ${TRUNCT_DATABASE_PORT:-5432}:5432
        environment:
            - POSTGRES_USER=${TRUNCT_DATABASE_USER}
            - POSTGRES_PASSWORD=${TRUNCT_DATABASE_PASSWORD}
            - POSTGRES_DB=${TRUNCT_DATABASE_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - trunct.io_net

    pg_admin:
        image: dpage/pgadmin4:2024-10-19-2
        depends_on:
            - postgres_db
        environment:
            - PGADMIN_DEFAULT_EMAIL=docker@localhost.com
            - PGADMIN_DEFAULT_PASSWORD=docker
        ports:
            - 8080:80
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - trunct.io_net

    air_development:
        image: cosmtrek/air:v1.61.1
        working_dir: /app
        depends_on:
            - postgres_db
        ports:
            - 3333:3333
        environment:
            - LOAD_ENV_FILE=true
        volumes:
            - ./:/app
        command:
            [
                "--build.cmd",
                "GOOS=linux CGO_ENABLED=0 GOARCH=amd64 GO111MODULE=on go build -buildvcs=false -o ./bin/api ./cmd/api",
                "--build.bin",
                "./bin/api",
            ]
        networks:
            - trunct.io_net

    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        volumes:
            - ./:/src/trunctio
        networks:
            - trunct.io_net
        depends_on:
            - postgres_db

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local

networks:
    trunct.io_net:
        driver: bridge
