// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: urls.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url, code, owner_id)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateURLParams struct {
	OriginalUrl string    `json:"original_url"`
	Code        string    `json:"code"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createURL, arg.OriginalUrl, arg.Code, arg.OwnerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findURLByCode = `-- name: FindURLByCode :one
SELECT id, code, owner_id, original_url, clicks, created_at, updated_at
FROM urls
WHERE code = $1
`

type FindURLByCodeRow struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	OwnerID     uuid.UUID `json:"owner_id"`
	OriginalUrl string    `json:"original_url"`
	Clicks      int32     `json:"clicks"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) FindURLByCode(ctx context.Context, code string) (FindURLByCodeRow, error) {
	row := q.db.QueryRow(ctx, findURLByCode, code)
	var i FindURLByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET original_url = $2, clicks = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, code, owner_id, original_url, clicks, created_at, updated_at
`

type UpdateURLParams struct {
	ID          uuid.UUID `json:"id"`
	OriginalUrl string    `json:"original_url"`
	Clicks      int32     `json:"clicks"`
}

type UpdateURLRow struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	OwnerID     uuid.UUID `json:"owner_id"`
	OriginalUrl string    `json:"original_url"`
	Clicks      int32     `json:"clicks"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (UpdateURLRow, error) {
	row := q.db.QueryRow(ctx, updateURL, arg.ID, arg.OriginalUrl, arg.Clicks)
	var i UpdateURLRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
